name:                cnt-mailer
version:             0.1.0.0
github:              "brhutchins/cnt-mailer"
license:             MIT
author:              "Barnaby Hutchins"
maintainer:          "bhutchins@gmail.com"
copyright:           "2021 Barnaby Hutchins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cnt-mailer#readme>

dependencies:
- base >= 4.7 && < 5
- smtp-mail
- cmdargs
- text
- mime-mail == 0.5.1

library:
  source-dirs: src

executables:
  cnt-mailer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cnt-mailer

tests:
  cnt-mailer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cnt-mailer
